### PR TITLE
Rewritten parts of server to ES6

### PR DESCRIPTION
**Pull request by eul721**
- Use local nodemon instead
- Added morgan loggin

### CODE REVIEW

**Comment by kevinxh** [comment]
Please check ES6 compatibility with mongoose.

Thanks~

**Comment by eul721** [comment]
@kevinxh ES6 still allows Javascript pre-ES6. I don't see any problem

**Comment by eul721** [comment]
[i.e. This is how others use it](https://github.com/KunalKapadia/express-mongoose-es6-rest-api/blob/master/server/models/user.js)

**Comment by kevinxh** [comment]
@eul721 ok, thats good. cuz I saw some weird notes earlier about ES6 integration on mongoose doc page. I guess that doesn't matter.

Thanks

**Pull request merged**
